[package]
name = "disco-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
disco-domain = { path = "../disco-domain" }
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
