[package]
name = "disco-tools"
version.workspace = true
edition.workspace = true

[dependencies]
disco-protocol = { path = "../disco-protocol" }
tokio = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
libc = "0.2"
serde = { workspace = true }
serde_json = { workspace = true }
