[package]
name = "disco-backends"
version.workspace = true
edition.workspace = true

[dependencies]
disco-core = { path = "../disco-core" }
disco-providers = { path = "../disco-providers" }
disco-tools = { path = "../disco-tools" }
async-trait = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio-util = { workspace = true }
futures-core = { workspace = true }
